runs:
  using: composite
  steps:
    # TODO: - uses: actions/checkout@v4.2.2
    - uses: DeLaGuardo/setup-clojure@13.1
      with:
        cli: 1.12.0.1488
    - uses: actions/cache@v4.2.0
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          .cpcache
        key: "${{hashFiles('deps.edn')}}"
