on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kondo:
    runs-on: ubuntu-latest
    uses: souenzzo/pedestal.jdk-httpserver/.github/workflows/setup.yml@use-action
    steps:
      - run: clojure -M:dev:kondo
  test-runner:
    runs-on: ubuntu-latest
    uses: souenzzo/pedestal.jdk-httpserver/.github/workflows/setup.yml@use-action
    steps:
      - run: clojure -M:dev:test-runner
  pedestal-container-tests:
    runs-on: ubuntu-latest
    uses: souenzzo/pedestal.jdk-httpserver/.github/workflows/setup.yml@use-action
    steps:
      - run: clojure -M:dev:pedestal-container-tests

## docker run --rm  -v.:/app:ro "-v$HOME/.m2:/root/.m2:ro" "-v$HOME/.gitlibs:/root/.gitlibs:ro" -w/app --mount type=tmpfs,dst=/app/.cpcache clojure:tools-deps-alpine clojure -M:dev:test-runner
