on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-runner:
    runs-on: ubuntu-latest
    container: clojure:tools-deps-alpine
    steps:
      - uses: actions/checkout@v4.2.2
      - run: clojure -M:dev:test-runner
