on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-runner:
    runs-on: ubuntu-latest
    container: clojure:tools-deps-alpine
    steps:
      - uses: actions/checkout@v4.2.2
      - run: clojure -M:dev:test-runner

## docker run --rm  -v.:/app:ro "-v$HOME/.m2:/root/.m2:ro" "-v$HOME/.gitlibs:/root/.gitlibs:ro" -w/app --mount type=tmpfs,dst=/app/.cpcache  -ti clojure:tools-deps-alpine clojure -M:dev:test-runner
