on: workflow_dispatch
jobs:
  test-runner:
    runs-on: ubuntu-latest
    # container:
      # image: clojure:tools-deps-alpine
    steps:
      - run: find .
      - run: env
      - run: clojure -M:dev:test-runner
